export const projects = [
   {
    title: "Sketch.ai",
    description: "A freehand tool where you can create your system design with AI.Use it to draw diagrams.",
    github: "https://github.com/Rohanvernekarr/sketchai",
    demo: "https://sketchai-xi.vercel.app/",
    status: "deployed",
    image: "/projects/sketch.png",
    techStack: ["Next.js", "React","Tailwind CSS", "Canvas API", "PostgreSql"],
  },
  {
    title: "SmartCV",
    description: "Full-stack AI web platform that helps users to create, customize, and optimize professional resumes. With built-in templates, live editing and AI-driven resume analysis.",
    github: "https://github.com/Rohanvernekarr/smartcv",
    demo: "https://smartcv-eta.vercel.app/",
    status: "deployed",
    image: "/projects/smart.png",
    techStack: ["Next.js", "Tailwind CSS", "Supabase", "AI"],
  },
  {
    title: "Poller",
    description: "Poller is a high-performance, full-stack polling platform built with Next.js and Prisma, featuring real-time analytics and a premium monochrome design. It includes a comprehensive admin dashboard for user management, detailed vote tracking, and automated interaction telemetry via PostHog.",
    github: "https://github.com/Rohanvernekarr/poller",
    demo: "",
    status: "in-progress",
    image: "/projects/poller.png",
    techStack: ["Next.js", "Tailwind CSS", "PostgreSql","Prisma", "PostHog"],
  },
   {
    title: "WarMonitor",
    description: "Real-time conflict monitoring platform aggregating news, social media, and official sources.With interactive map.",
    github: "https://github.com/Rohanvernekarr/warmonitor",
    demo: "https://warmonitor-eta.vercel.app/",
    status: "deployed",
    image: "/projects/war1.png",
    techStack: ["Next.js", "React", "Typescript","API"],
  },
    {
    title: "StrangerLoop",
    description: "Connect with random strangers, End-to-end Encrypted. Built with Next.js + WebRTC.",
    github: "https://github.com/Rohanvernekarr/StrangerLoop",
    demo: "https://stranger-loop.vercel.app/",
    status: "deployed",
    image: "/projects/loop.png",
    techStack: ["Next.js", "TypeScript", "WebRTC", "Tailwind CSS"],
  },
    {
    title: "CodeHub",
    description: "A GitHub alternative built using lovable.dev",
    github: "https://lovable.dev/projects/30c4b5ad-961a-41cc-b3dc-c43b4a30bf79",
    demo: "https://codehubv1.lovable.app/",
    status: "deployed",
    image: "/projects/codehub.png",
    techStack: ["TypeScript", "React", "Tailwind CSS", "Supabase", "Lovable.dev"],
  },
   {
    title: "NeonVerse",
    description: "3D cosmic experience using React Three Fiber, Drei, and GSAP. A storytelling journey through the stars.",
    github: "https://github.com/Rohanvernekarr/NeonVerse",
    demo: "",
    status: "in-progress",
    image: "/projects/space.png",
    techStack: ["React Three Fiber", "GSAP", "WebGL"],
  },
 
    {
    title: "Githive",
    description: "GitHub-powered project hub to manage, tag, and search repos easily. Built with Next.js + GitHub API.",
    github: "https://github.com/Rohanvernekarr/githive",
    demo: "https://githive.vercel.app/",
    status: "deployed",
    image: "/projects/githuve.png",
    techStack: ["Next.js", "TypeScript", "GitHub API", "Tailwind CSS"],
  },
  {
    title: "ContestTracker",
    description: "Track competitive programming contests from Codeforces, LeetCode, AtCoder and more. Alerts and calendar integration.",
    github: "https://github.com/Rohanvernekarr/contesttracker",
    demo: "https://contesttracker-ruby.vercel.app/",
    status: "deployed",
    image: "/projects/contest.png",
    techStack: ["MongoDB", "Express", "React", "Node.js"],
  },
 
  {
    title: "FusionChat",
    description: "Real-time chat app built using Socket.io and MongoDB with custom avatars and group support.",
    github: "https://github.com/Rohanvernekarr/FusionChat",
    demo: "https://fusion-chat-plum.vercel.app/",
    status: "deployed",
    image: "/projects/rog.jpg",
    techStack: ["React", "Socket.io", "MongoDB", "Express"],
  },
  {
    title: "NewsReader",
    description: "Minimalist Hacker News reader built for focus and speed. Keyboard-first UX with search and filters.",
    github: "https://github.com/Rohanvernekarr/hackernewsreader",
    demo: "https://hackernewsreader.vercel.app/",
    status: "deployed",
    image: "/projects/news.png",
    techStack: ["Next.js", "Hacker News API", "TypeScript"],
  },
  {
    title: "CollegeAdmissionPortal",
    description: "An Application with three different roles for colleges to admit students to their courses. Fully vibe coded.",
    github: "https://github.com/Rohanvernekarr/collegeadmission",
    demo: "",
    status: "deployed",
    image: "/projects/rog1.jpg",
    techStack: ["Django", "React", "Bootstrap", "PostgreSQL"],
  },
  {
    title: "BioMLStudio",
    description: "AI-based no-code bioinformatics platform for protein & DNA sequence analysis.",
    github: "https://github.com/Rohanvernekarr/biomlstudio",
    demo: "",
    status: "in-progress",
    image: "/projects/rog2.jpg",
    techStack: ["React", "Python", "MongoDB", "ML"],
  },
  {
    title: "Coinly",
    description: "Crypto dashboard and portfolio tracker using MERN stack and CoinGecko API. Graphs and real-time price updates.",
    github: "https://github.com/Rohanvernekarr/coinlycrypto",
    demo: "",
    status: "in-progress",
    image: "/projects/crypto.png",
    techStack: ["MongoDB", "Express", "React", "Node.js", "CoinGecko API"],
  },
  {
    title: "Vibeoo",
    description: "Vibeoo is an AI-powered extension that summarizes videos and generates smart timestamps for faster, focused viewing.",
    github: "https://github.com/Rohanvernekarr/vibeoo",
    demo: "",
    status: "in-progress",
    image: "/projects/rog4.png",
    techStack: ["Chrome Extension", "AI", "JavaScript"],
  },
  {
    title: "TruthLens",
    description: "Fake news detection extension using AI and fact-check APIs. Built with Python and Flask.",
    github: "https://github.com/Rohanvernekarr/truthlens",
    demo: "",
    status: "in-progress",
    image: "/projects/cat.png",
    techStack: ["Python", "Flask", "AI", "Chrome Extension"],
  },
 
]