import {
  Container, Palette, Code2, Zap, Layers, Server,
  Database, Cloud, GitBranch, Box, Globe, Cpu,
  Network, Braces, TerminalSquare, Boxes, Hammer,
  BrainCircuit, FlaskConical, MonitorSmartphone,
} from "lucide-react";

export const techStack = [
  {
    title: "Languages",
    icon: Code2,
    items: [
      { name: "JavaScript", icon: Braces },
      { name: "TypeScript", icon: Code2 },
      { name: "Python",     icon: TerminalSquare },
      { name: "C++",        icon: Code2 },
      { name: "C",          icon: Code2 },
    ],
  },
  {
    title: "Technologies",
    icon: Globe,
    items: [
      { name: "HTML",        icon: Globe },
      { name: "CSS",         icon: Palette },
      { name: "React.js",    icon: Braces },
      { name: "Next.js",     icon: Globe },
      { name: "Tailwind CSS",icon: Palette },
      { name: "Framer Motion",icon: Zap },
      { name: "Redux",       icon: Boxes },
      { name: "Vite",        icon: TerminalSquare },
      { name: "Express.js",  icon: Network },
      { name: "Node.js",     icon: Server },
      { name: "FastAPI",     icon: FlaskConical },
      { name: "GraphQL",     icon: Layers },
      { name: "REST",        icon: Layers },
    ],
  },
  {
    title: "Database",
    icon: Database,
    items: [
      { name: "PostgreSQL", icon: Database },
      { name: "MongoDB",    icon: Database },
      { name: "MySQL",      icon: Database },
      { name: "Prisma",     icon: Cpu },
      { name: "Supabase",   icon: Database },
      { name: "Firebase",   icon: Cloud },
      { name: "Upstash Redis", icon: Database },
    ],
  },
  {
    title: "Cloud & DevOps",
    icon: Cloud,
    items: [
      { name: "AWS",        icon: Cloud },
      { name: "GCP",        icon: Cloud },
      { name: "Vercel",     icon: Cloud },
      { name: "Supabase",   icon: Cloud },
      { name: "Jenkins",    icon: GitBranch },
      { name: "Docker",     icon: Container },
      { name: "CI/CD",      icon: GitBranch },
      { name: "Railway",    icon: Server },
      { name: "VPS",         icon: Server },
    ],
  },
  {
    title: "Developer Tools",
    icon: Hammer,
    items: [
      { name: "GitHub",          icon: GitBranch },
      { name: "Docker",          icon: Container },
      { name: "VS Code",         icon: MonitorSmartphone },
      { name: "Postman",         icon: Box },
      { name: "Android Studio",  icon: MonitorSmartphone },
      { name: "pnpm",            icon: TerminalSquare },
    ],
  },
  {
    title: "AI & GenAI",
    icon: BrainCircuit,
    items: [
      { name: "LangChain",         icon: BrainCircuit },
      { name: "LangGraph",         icon: BrainCircuit },
      { name: "RAG",               icon: Layers },
      { name: "NLP",               icon: BrainCircuit },
      { name: "Generative AI",     icon: Zap },
      { name: "AI Agents",         icon: Cpu },
      { name: "Prompt Engineering",icon: TerminalSquare },
      { name: "OpenAI",            icon: BrainCircuit },
    ],
  },
];
